### ISSUE TITLE
HA User

### ISSUE THREAD

**Issue by ChrisPiel70** [SAIC-iSmart-API/saic-home-assistant-addon#1]
Hello,

FYI

as a Home Assistant User with a MG Marvel-R i am very interestet in this Project. I have already used these clients from this project:

ismart-api-gateway-0.0.3-full.jar <= HA "HTTP" sensors
saic-ismart-http-gateway-0.2.0-full.jar <= HA "REST" sensors
saic-ismart-mqtt-gateway-0.2.0-full.jar <= HA "MQTT" sensors
and
saic-python-mqtt-gateway-main/mqtt_gateway.py <= HA "MQTT" sensors

with different & mixed results and success. 

If I can contribute or help in any way ( Testing, HA Configuration ) or whatever else please let me know.

Keep up the great work. Its a shame that SAIC ( as well as others ) don't help.

Best Regards
Chris

**Comment by Tonno87** [comment]
Hi, the SAIC MQTT Gateway (Python) is available now via addon (version 0.2.0). Try it out :)
