### ISSUE TITLE
Home Assitant Addon Not Starting 

### ISSUE THREAD

**Issue by ceaswaran** [SAIC-iSmart-API/saic-home-assistant-addon#10]
I am from India 
Tried Installing this Addon after which whe I START I get the follwoing error

Please help

`2023-05-30 17:45:49,042 return code: 15011, message: The account is not registered.
Traceback (most recent call last):
  File "/usr/src/app/./mqtt_gateway.py", line 427, in run
    login_response_message = self.saic_api.login()
  File "/usr/local/lib/python3.10/site-packages/saic_ismart_client/saic_api.py", line 113, in login
    raise SaicApiException(login_response_message.body.error_message.decode(),
saic_ismart_client.saic_api.SaicApiException: return code: 15011, message: The account is not registered.
return code: 15011, message: The account is not registered.`

**Comment by Tonno87** [comment]
Hi, take a look at #6.

You need to find out your SAIC_URI to connect to the right Server.

**Comment by Tonno87** [comment]
It seems that MG Motors India doesn't allow a login with email, but both gateways need this to work. So at the moment there is no way to help you...

**Comment by Tonno87** [comment]
Found a solution for your problem:

Login with phone number: yyy-xxxxxxxx

yyy = country like 49 for Germany
xxxxxxxx = phone number like entered in your app.


But: you need your Saic_Url for India...

**Comment by Tonno87** [comment]
You could try the following URI: iov-tap.mgindia.co.in
Try our phone number as a username.

**Comment by ceaswaran** [comment]
@Tonno87 Thanks of the reply

I have update above Url or India
Use username as : +91-9898989898

Still I get the following error
`2023-06-09 16:22:31,445 return code: 15011, message: The account is not registered.
Traceback (most recent call last):
  File "/usr/src/app/./mqtt_gateway.py", line 427, in run
    login_response_message = self.saic_api.login()
  File "/usr/local/lib/python3.10/site-packages/saic_ismart_client/saic_api.py", line 113, in login
    raise SaicApiException(login_response_message.body.error_message.decode(),
saic_ismart_client.saic_api.SaicApiException: return code: 15011, message: The account is not registered.
return code: 15011, message: The account is not registered.`

**Comment by tisoft** [comment]
Remove the `+`

**Comment by Tonno87** [comment]
I think you have to wait for 0.2.3 to try it out. The python gateway is buggy at the moment, so I reverted it to 0.2.1 which cannot change the uri.

The EU version of the mg app allows you to choose your country code, but the India app does not.

**Comment by ceaswaran** [comment]
> Remove the `+`

Yes I removed +
Tried removing + Dint work
Just tried 91=XXXXXXXX Dint work
Also tried 091-XXXXXXX Dint work
:(

**Comment by Tonno87** [comment]
[Setting SAIC_URI in docker-compose.yml](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/issues/18)

You can install the addon yourself by ssh or smb to the /addon folder of home assistant and change the version to 0.2.2.
But after that there is a new [issue](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/issues/22) ... :)

**Comment by Tonno87** [comment]
0.2.3 is online. Try it out :)

**Comment by ceaswaran** [comment]
Which add on is this 0.2.3?
I see diffrent version still

![image](https://github.com/SAIC-iSmart-API/saic-home-assistant-addon/assets/40624146/7393bc0b-882e-4ce3-b64b-0c988c2b1679)

**Comment by Tonno87** [comment]
Python Gateway. Go to the Addon-Store in HA and check for updates:

![Screenshot_20230610-182422.png](https://github.com/SAIC-iSmart-API/saic-home-assistant-addon/assets/59800400/d7dbe8d5-d090-4bb8-adf2-20fc5a85061f)

**Comment by ceaswaran** [comment]
@Tonno87 MAnaged to geet lates build

I get the following Error

`2023-06-10 21:59:48,173 application ID: 511, protocol version: 25857, message: The service is not available,please try again later~ result code: 702
2023-06-10 21:59:49,672 application ID: 511, protocol version: 25857, message: The service is not available,please try again later~ result code: 702
2023-06-10 21:59:49,925 application ID: 511, protocol version: 25857, message: The service is not available,please try again later~ result code: 702`

**Comment by ceaswaran** [comment]
`Exception in thread Thread-1 (_thread_main):
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3039, in _packet_handle
    return self._handle_connack()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3138, in _handle_connack
    on_connect(
  File "/usr/src/app/mqtt_publisher.py", line 51, in __on_connect
    self.client.subscribe(f'{basic_topic}/refresh/mode/set')
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1491, in subscribe
    raise ValueError('Invalid subscription filter.')
ValueError: Invalid subscription filter.
2023-06-10 22:02:34,684 Registering for abnormal messages
2023-06-10 22:02:34,968 Registering for moving messages
2023-06-10 22:02:35,268 Registering for region messages
2023-06-10 22:02:35,552 Registering for engineStart messages
2023-06-10 22:02:35,818 Failed to register for startVehicleStatus messages
2023-06-10 22:02:36,079 Failed to register for offCar messages
2023-06-10 22:02:36,351 Failed to register for speeding messages
Traceback (most recent call last):
  File "/usr/src/app/./mqtt_gateway.py", line 720, in <module>
    mqtt_gateway.run()
  File "/usr/src/app/./mqtt_gateway.py", line 400, in run
    self.publisher.publish_str(f'{info_prefix}/brand', vin_info.brand_name.decode())
  File "/usr/src/app/mqtt_publisher.py", line 126, in publish_str
    self.publish(msg)
  File "/usr/src/app/mqtt_publisher.py", line 109, in publish
    self.client.publish(msg.topic, msg.payload, retain=True)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1233, in publish
    raise ValueError('Publish topic cannot contain wildcards.')
ValueError: Publish topic cannot contain wildcards.`

**Comment by Tonno87** [comment]
can you show us your options entries?

**Comment by ceaswaran** [comment]
> can you show us your options entries?
Sorry I didn't get you
U mean configuration Tab of the Addon?

**Comment by ceaswaran** [comment]
![image](https://github.com/SAIC-iSmart-API/saic-home-assistant-addon/assets/40624146/6dcf2b29-a227-410d-92ec-86cc1f3c07b2)

**Comment by Tonno87** [comment]
Please try your phone number with 0 instead of 091-... Like entering into your app.

Hope it helps.

**Comment by Tonno87** [comment]
Tisoft posted this on the discussion board: [iSmart Thailand](https://github.com/orgs/SAIC-iSmart-API/discussions/8#discussioncomment-6145855)

```
Thailand only supports phone numbers. The format is a bit different to EU/AU/NZ. With the Java MQTT Gateway it should work to prefix your phone number with 0's until the whole string is exactly 50 characters long. (e.g.00000000000000000000000000000000000000000123456789) I haven't checked if the Python MQTT Gateway would accept that.

I assume the same format should be working in the India version, but all versions of the India App I could find, are encrypted and I can't get the source code, so I can't verify.
```

**Comment by ceaswaran** [comment]
> Tisoft posted this on the discussion board: [iSmart Thailand](https://github.com/orgs/SAIC-iSmart-API/discussions/8#discussioncomment-6145855)
> 
> ```
> Thailand only supports phone numbers. The format is a bit different to EU/AU/NZ. With the Java MQTT Gateway it should work to prefix your phone number with 0's until the whole string is exactly 50 characters long. (e.g.00000000000000000000000000000000000000000123456789) I haven't checked if the Python MQTT Gateway would accept that.
> 
> I assume the same format should be working in the India version, but all versions of the India App I could find, are encrypted and I can't get the source code, so I can't verify.
> ```
**I see this log in (java) MQTT add on
Does this means its working?
How do I fetch or see further data??

Please help**

`Value for option option '--abrp-user-token' (<String=String>) should be in KEY=VALUE[,KEY=VALUE]... format but was 
Usage: ismart-mqtt-gateway [-hV] [--abrp-api-key=<abrpApiKey>] [-c=<config>]
                           [-m=<mqttUri>] [--mqtt-password=<mqttPassword>]
                           [--mqtt-user=<mqttUser>] [-p=<saicPassword>]
                           [-s=<saicUri>] [-u=<saicUser>]
                           [--abrp-user-token=<String=String>[,
                           <String=String>...]]...
      --abrp-api-key=<abrpApiKey>
                             The API key for the A Better Route Planer
                               telemetry API.
                             Default is the open source telemetry API key
                               8cfc314b-03cd-4efe-ab7d-4431cd8f2e2d
                             Environment Variable: ABRP_API_KEY
      --abrp-user-token=<String=String>[,<String=String>...]
                             The mapping of VIN to ABRP User Token.
                             Multiple mappings can be provided seperated by ,
                             Example: LSJXXXX=12345-abcdef,LSJYYYY=67890-ghijkl
                             Environment Variable: ABRP_USER_TOKEN
  -c, --config=<config>      The config file to use. Options can be overridden
                               by cli parameters and environment variables
  -h, --help                 Show this help message and exit.
  -m, --mqtt-uri=<mqttUri>   The URI to the MQTT Server.
                             Environment Variable: MQTT_URI
      --mqtt-password=<mqttPassword>
                             The MQTT password.
                             Environment Variable: MQTT_PASSWORD
      --mqtt-user=<mqttUser> The MQTT user name.
                             Environment Variable: MQTT_USER
  -p, --saic-password=<saicPassword>
                             The SAIC password.
                             Environment Variable: SAIC_PASSWORD
  -s, --saic-uri=<saicUri>   The SAIC uri.
                             Environment Variable: SAIC_URI
                             Default is the European Production Endpoint: https:
                               //tap-eu.soimt.com
  -u, --saic-user=<saicUser> The SAIC user name.
                             Environment Variable: SAIC_USER
  -V, --version              Print version information and exit.`

**Comment by Tonno87** [comment]
Seems to be similar to this [problem](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/issues/18#issuecomment-1575703819)

If the fields are empty the gateway won't run.

**Comment by Tonno87** [comment]
This should work:

![Screenshot_20230613-062801.png](https://github.com/SAIC-iSmart-API/saic-home-assistant-addon/assets/59800400/207896dc-b341-4d4e-ac00-1d23657ed73c)

**Comment by sheminasalam** [comment]
> > Tisoft posted this on the discussion board: [iSmart Thailand](https://github.com/orgs/SAIC-iSmart-API/discussions/8#discussioncomment-6145855)
> > ```
> > Thailand only supports phone numbers. The format is a bit different to EU/AU/NZ. With the Java MQTT Gateway it should work to prefix your phone number with 0's until the whole string is exactly 50 characters long. (e.g.00000000000000000000000000000000000000000123456789) I haven't checked if the Python MQTT Gateway would accept that.
> > 
> > I assume the same format should be working in the India version, but all versions of the India App I could find, are encrypted and I can't get the source code, so I can't verify.
> > ```
> 
> **I see this log in (java) MQTT add on, Does this means its working? How do I fetch or see further data?? Please help**
> 
> `Value for option option '--abrp-user-token' (<String=String>) should be in KEY=VALUE[,KEY=VALUE]... format but was Usage: ismart-mqtt-gateway [-hV] [--abrp-api-key=<abrpApiKey>] [-c=<config>] [-m=<mqttUri>] [--mqtt-password=<mqttPassword>] [--mqtt-user=<mqttUser>] [-p=<saicPassword>] [-s=<saicUri>] [-u=<saicUser>] [--abrp-user-token=<String=String>[, <String=String>...]]... --abrp-api-key=<abrpApiKey> The API key for the A Better Route Planer telemetry API. Default is the open source telemetry API key 8cfc314b-03cd-4efe-ab7d-4431cd8f2e2d Environment Variable: ABRP_API_KEY --abrp-user-token=<String=String>[,<String=String>...] The mapping of VIN to ABRP User Token. Multiple mappings can be provided seperated by , Example: LSJXXXX=12345-abcdef,LSJYYYY=67890-ghijkl Environment Variable: ABRP_USER_TOKEN -c, --config=<config> The config file to use. Options can be overridden by cli parameters and environment variables -h, --help Show this help message and exit. -m, --mqtt-uri=<mqttUri> The URI to the MQTT Server. Environment Variable: MQTT_URI --mqtt-password=<mqttPassword> The MQTT password. Environment Variable: MQTT_PASSWORD --mqtt-user=<mqttUser> The MQTT user name. Environment Variable: MQTT_USER -p, --saic-password=<saicPassword> The SAIC password. Environment Variable: SAIC_PASSWORD -s, --saic-uri=<saicUri> The SAIC uri. Environment Variable: SAIC_URI Default is the European Production Endpoint: https: //tap-eu.soimt.com -u, --saic-user=<saicUser> The SAIC user name. Environment Variable: SAIC_USER -V, --version Print version information and exit.`

Is this working now? I am still getting the error The country code not exist !. Hope you can help me sort this.
