### ISSUE TITLE
View 2 cars in Home Assistant

### ISSUE THREAD

**Issue by gawin77** [SAIC-iSmart-API/saic-home-assistant-addon#109]
Hello,

Thanks for integration, it works perfectly with my MG4.

Now, I want to have my second MG4 in Home Assistant but i don't duplicate the add on.

It's possible to add another vehicle in the existing add on ?

Thanks

**Comment by nanomad** [comment]
Sure, just add the car to the same account then restart the addon

Il Dom 13 Ott 2024, 07:42 gawin77 ***@***.***> ha scritto:

**Comment by gawin77** [comment]
Thank you.

I discovered that not limited at one car for one account.

I added my second car on my main account , it's perfect.

I close the subject
