### ISSUE TITLE
Showing data in HASS

### ISSUE THREAD

**Issue by j0hnby** [SAIC-iSmart-API/saic-home-assistant-addon#13]
Hey - thanks for working on this, it's awesome. 

I have set up the Python instance, and it's showing as up, and in EMQX (my MQTT) it's showing the subscription - but I am struggling to get data into HASS.....any pointers on this at all please?

**Comment by Tonno87** [comment]
Hi, please take a look into the wiki. You need to create some sensors in your home assistant configuration. In the future there will be an integration for easy setup.
