### ISSUE TITLE
can't to version: 0.2.2 

### ISSUE THREAD

**Issue by Krogstrup** [SAIC-iSmart-API/saic-home-assistant-addon#16]
Hi 
i have problems with getting the add-on to upgrade to version: 0.2.2

my add-on was on version: 0.2.2 yesterday but suddenly my home assistant tells me that there was a upgrade but it downgraded instead. and now i can't get it to upgrade again.

**Comment by Tonno87** [comment]
Hi, actually there is a bug in 0.2.2. The gateway crashes by retrieving a new message like engineStart. So I reverted the update to force a downgrade to the last working version 0.2.1.

**Comment by Tonno87** [comment]
Look at this issue [#22](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/issues/22)

**Comment by Krogstrup** [comment]
Ahh, Thanks for clarification and quick response :)
