### ISSUE TITLE
Password invalid, max password length not honored

### ISSUE THREAD

**Issue by DCSBL** [SAIC-iSmart-API/saic-home-assistant-addon#18]
In the iOS app there is (frustratingly) a password length limit of 16 characters.

My password manager had a longer password stored, but when it auto fills it apparently truncates the rest. This addon allows longer password and then it yells that my password is invalid (which it is).

I think it it nice to keep somehow warn the user if they enter a longer password. But I am not sure where we may add that.

**Comment by tisoft** [comment]
Just for reference, this is the regex the app checks for passwords: `^(?![0-9]+$)(?![a-zA-Z]+$)[0-9A-Za-z]{8,16}$`

* may not be only numbers
* may not be only letters
* may only contain numbers and small and big letters
* must be 8-16 characters long
