### ISSUE TITLE
.../refresh/mode/set force gives "Unsupported topic"

### ISSUE THREAD

**Issue by DreamT80** [SAIC-iSmart-API/saic-home-assistant-addon#2]
(opening separate issues for some things I found, not to spam but to give some structure).

The command `saic/[user]/vehicles/[vin]/refresh/mode/set force` command works fine on the saic-python-mqtt-gateway standalone version , but gives `Command failed. Unsupported topic refresh/mode` on this addon.

Maybe it's a known version issue, i.e. the "base version" used in the addon is behind the standalone version?

**Comment by tisoft** [comment]
The add-on uses the java mqtt gateway and I have not yet added support for `saic/[user]/vehicles/[vin]/refresh/mode/set force` yet.

You can use `saic/[user]/vehicles/[vin]/drivetrain/hvBatteryActive/set true` in the java mqtt gateway, to achieve the same currently.

**Comment by DreamT80** [comment]
Ok, I see. I used the alternative solution you proposed, which worked as expected.
