### ISSUE TITLE
More of a question than an issue.

### ISSUE THREAD

**Issue by Kilberz** [SAIC-iSmart-API/saic-home-assistant-addon#21]
So I've got this up and running with HA - I can the messages coming in thick and fast with MQTT and I'll be using the values to create sensors.

My questions is, will the out of the box config for this drain the battery or is this just processing the data the vehicle would otherwise put out?

**Comment by Tonno87** [comment]
Hi, at the moment the python gateway in version 0.2.3 or 0.2.4 will only pull data from your car if you are driving or charging with openWB. Another way is to send "force" to the refresh mode topic.

The java gateway will implement this feature with the next stable version. You can change the active or inactive time to your favorite value. [Releases](https://github.com/SAIC-iSmart-API/saic-java-client/releases)
