### ISSUE TITLE
0.3.0 auto-discovery, missing soc_kwh

### ISSUE THREAD

**Issue by DreamT80** [SAIC-iSmart-API/saic-home-assistant-addon#27]
First of all, the new auto-discovery works great. It really simplifies the process of working with the addon. Hats of for this!

I discovered (no pun intended) that soc_kwh isn't included in the auto-discovery. I know that we have the soc percentage to work with, but it's quite nice to have the actual energy level in kilowatts to work with. (for instance, i use range/soc_kwh to estimate "kWh per kilometer"). Would it be possible to add soc_kwh in the auto discovery?

**Comment by DreamT80** [comment]
Ok, but i'm talking about energy level. It's available in the MQTT response:

`saic/[user]/vehicles/[vin]/drivetrain/soc_kwh`

But I can't find it as an autodiscovery value.

**Comment by Tonno87** [comment]
Sorry, my mistake. You are right, this value wasn't added to the auto discovery. But i think it shouldn't be a problem to add it to 0.4.0.

**Comment by DreamT80** [comment]
> Sorry, my mistake. You are right, this value wasn't added to the auto discovery. But i think it shouldn't be a problem to add it to 0.4.0.

Ok, sounds great :)

**Comment by Tonno87** [comment]
The fix is on the way: [PR](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/pull/69)

Attention: The value of soc_kwh is wrong because it's based on the wrong capacity in iSmart (72.5kWh). So you need a factor to correct this. At the moment you need a template sensor to do this.

**Comment by DreamT80** [comment]
> The fix is on the way: [PR](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/pull/69)
> 
> Attention: The value of soc_kwh is wrong because it's based on the wrong capacity in iSmart (72.5kWh). So you need a factor to correct this. At the moment you need a template sensor to do this.

Great! Actually, I think that 72.5 is correct in my case, but I will double check this and create a template sensor if needed.
