### ISSUE TITLE
Not getting any updated values anymore

### ISSUE THREAD

**Issue by Jonathandenb** [SAIC-iSmart-API/saic-home-assistant-addon#29]
Since a few days, I'm not getting any updated values anymore. Reloading the integration or restarting Home-assistent doens't help. A drive didn't cause any updates on any of the sensors. Also my GPS location is not updating. Is this a known issue, or is there something on my side I can do to fix this?

**Comment by Tonno87** [comment]
Hi, we need the log to help you. Please post it without e-mail or vin

**Comment by Jonathandenb** [comment]
Issue seems fixed after several restarts.
