### ISSUE TITLE
saic/[user]/messages/* gets updated constantly

### ISSUE THREAD

**Issue by DreamT80** [SAIC-iSmart-API/saic-home-assistant-addon#3]
The messages in  saic/[user]/messages/  gets updated every second, even if the info isn't changed.

I don't know if it has to do with that you are supposted to mark the messages as read or something?

Maybe it's not a big issue, I just wondered if it puts unnecessary strain on the MQTT broker or so. (I guess that this is only happening on the "local side" of the gateway, i.e. it doesn't generate traffic to/from the SAIC API)

**Comment by Tonno87** [comment]
We need to wait for some improvements on the [saic-java-client](https://github.com/SAIC-iSmart-API/saic-java-client) project.
