### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by kevinVl** [SAIC-iSmart-API/saic-home-assistant-addon#32]
I've installed the addon to my Home Assistant, but on start I receive the following error
Traceback (most recent call last):
  File "/usr/src/app/./mqtt_gateway.py", line 269, in run
    login_response_message = self.saic_api.login()
  File "/usr/local/lib/python3.10/site-packages/saic_ismart_client/saic_api.py", line 123, in login
    raise SaicApiException(login_response_message.body.error_message.decode(),
saic_ismart_client.saic_api.SaicApiException: return code: 15018, message: Incorrect password. You may have another 4 attempts of the day, please try again.
return code: 15018, message: Incorrect password. You may have another 4 attempts of the day, please try again.

I have verified the username (email) and the password by logging out the app and try the same credentials and there they work.
My password does have a "?" in it, could this be an issue?

URI used is the default one as I'm based in EU/belgium https://tap-eu.soimt.com

**Comment by tisoft** [comment]
Yea the ? could be the issue. The app filters out any characters it does not support and never sends them to the server. Try with leaving the ? out.

**Comment by kevinVl** [comment]
Yes it was the ? In the password
