### ISSUE TITLE
How to identify URI for other countries

### ISSUE THREAD

**Issue by nickh66** [SAIC-iSmart-API/saic-home-assistant-addon#33]
Hi,
I'm really really hoping i can use this addon to bring in my MG iSmart data for my vehicle in Australia.  So far the default settings fail to login with my existing iSmart credentials using the default URI that appears to be for the EU region.  I was wondering if there is a way to determine what the correct URI should be for vehicles sold in Australia.  I did so far try https://tap-au.soimt.com because i find i could get a ping reply from that address but still the log for the addon returns failed login attempt.
I have no clue how to help progress this addon for use in my country so any suggestions on where i should look would be grateful.
Regards
Nick

**Comment by spcloudguy** [comment]
I'm using https://tap-au.soimt.com with an Australian MG ZS EV so you're using the correct URL.

**Comment by nickh66** [comment]
Hi, That's great news.  Which of the 2 MQTT based add-on options did you use, java or python?  Did it just accept the same saic login credentials you used in the iSmart app?

**Comment by CRMStanna** [comment]
I have a really dumb question that I have tried finding the answer to before coming here.  If I have installed the add on via the add on store, where do I go and put the correct URL.  I can't seem find that within Home Assistant - I tried digging around with Studio Code server, but can't find the config file for the addon.
Thanks for any help pointing me in the right direction.
