### ISSUE TITLE
HVAC don't work

### ISSUE THREAD

**Issue by nesbeal** [SAIC-iSmart-API/saic-home-assistant-addon#34]
Hello,

First, thank you for your work. I had no issues integrating it into my Home Assistant, and your integration has addressed many limitations (one MG app per car).

I've noticed just one issue: it's not possible to activate the air conditioning when the vehicle is stationary and locked. Yet, this can be done from the MG app (for up to 10 minutes).

The thermostat is present, but as soon as I click "on", it automatically switches back to "off", the same goes for other modes. Is this related to the sensor.remote_climate_state (always in off)?

**Comment by Tonno87** [comment]
Is this error still present?

**Comment by nesbeal** [comment]
No thank you !!!
After update SAIC new version , all running !!!
Your are the master!
