### ISSUE TITLE
Front window heating enables "Blowing only"

### ISSUE THREAD

**Issue by DreamT80** [SAIC-iSmart-API/saic-home-assistant-addon#40]
I'm not sure if I should put the issue here or in one of the other repositories. But I'll start here, since I discovered it in HA.

First of all, I have an. MG ZS EV -22. I'm using the latest version of the HA addon (0.4.5).

When I enable switch.[vin]_front_window_defroster_heating, the "Blowing only" mode gets activated instead.

The MQTT broker first says 
topic: `saic/[email]/vehicles/[vin]/climate/remoteClimateState/set`
value: `front`

...and after a while says `Message 19 received at saic/[email]/vehicles/[vin]/climate/remoteClimateState at 10:46 : blowingOnly`

The HA log says
`[  INFO  ] A/C will be set to front seats only - __main__` (which also is incorrect, it isn't the seats that are heated)

However, actually enabling the blowing only (via `switch.[vin]_vehicle_climate_fan_only`) doesn't work:

`Message 26 received at saic/[email]/vehicles/[vin]/climate/remoteClimateState/set at 10:47 :
blowingOnly`

`Message 27 received at saic/[email]/vehicles/[vin]/climate/remoteClimateState/result at 10:47 :
Failed: Unsupported payload blowingOnly`

**Comment by Tonno87** [comment]
```
                case mqtt_topics.CLIMATE_REMOTE_CLIMATE_STATE:
                    match msg.payload.decode().strip().lower():
                        case 'off':
                            LOG.info('A/C will be switched off')
                            self.saic_api.stop_ac(self.vin_info)
                        case 'blowingOnly':
                            LOG.info('A/C will be set to blowing only')
                            **self.saic_api.start_ac_blowing(self.vin_info)**
                        case 'on':
                            LOG.info('A/C will be switched on')
                            self.saic_api.start_ac(self.vin_info,
                                                   temperature_idx=self.vehicle_state.get_ac_temperature_idx())
                        case 'front':
                            LOG.info("A/C will be set to front seats only")
                            **self.saic_api.start_ac_blowing(self.vin_info)**
```
Seems that both values use the same command: self.saic_api.start_ac_blowing(self.vin_info)

**Comment by Tonno87** [comment]
The right command for case "front" should be: self.saic_api.start_front_defrost(self.vin_info).

**Comment by tosate** [comment]
Thank you @Tonno87 for hint.

**Comment by DreamT80** [comment]
I can confirm that it's working with the new release. Great!
