### ISSUE TITLE
Logout der ISmart App

### ISSUE THREAD

**Issue by 00Twister00** [SAIC-iSmart-API/saic-home-assistant-addon#42]
Hallo, 

wenn das Addon läuft werde ich aus der ISmart App auf dem Handy abgemeldet, hat jemand dazu eine Lösung?

Gruß Twister

**Comment by Tonno87** [comment]
Hi. Da nur eine Instanz zur gleichen Zeit möglich ist gibt es dafür keine Lösung. 

Gruß
