### ISSUE TITLE
Request for Force Update Command in Python MQTT Gateway

### ISSUE THREAD

**Issue by acmeGR** [SAIC-iSmart-API/saic-home-assistant-addon#43]
### Issue Description
I am currently using the Python version of the SAIC MQTT Gateway and I am looking for a way to manually force the gateway to update the vehicle's status.

### Previous Reference
I found a command in a [previous issue](https://github.com/SAIC-iSmart-API/saic-home-assistant-addon/issues/2) for the Java version that seems to force an update: saic/[user]/vehicles/[vin]/refresh/mode/set force, But I didnt manage to force update. It is very possible that I didn'd understand somehting. 

![image](https://github.com/SAIC-iSmart-API/saic-home-assistant-addon/assets/39457124/3ba355b2-0084-41a6-adab-5d4d8001c4fb)

I would be gratefull if I could have some instructions on what I am doing wrong.

### Environment
- Home Assistant Version: 2023.11.3
- SAIC MQTT Gateway Version (Python): version: 0.4.5
- Additional context in case it matters, in saic_user I have my phone.

**Comment by Tonno87** [comment]
Please move the word "force" to the Payload section. The topic is xxx/refresh/mode/set, force is the payload
