### ISSUE TITLE
Please add decimal point to lat / long values

### ISSUE THREAD

**Issue by jivesinger** [SAIC-iSmart-API/saic-home-assistant-addon#50]
MQTT lat / long data contains no decimal points rendering Home Assistant unable to render the location when used as a device tracker.
Can a decimal point be inserted in the values please.

(Using the Python version)

**Comment by Tonno87** [comment]
By using the python gateway there's already a device tracker (mqtt autodiscovery). Take a look at the mqtt integration in Home Assistant.
Additionally there are three mqtt topics which contain the position, longitude and latitude with a decimal point.

So there's nothing to do for me :)

**Comment by Tonno87** [comment]
![image](https://github.com/SAIC-iSmart-API/saic-home-assistant-addon/assets/59800400/d15eaf17-af3c-491c-8165-599916f006bc)

**Comment by jivesinger** [comment]
Wow ! I have no idea how i missed that !

Well, thank-you for pointing that out AND for developing this add-on.
It's very much appreciated.
