### ISSUE TITLE
Error 1000020, message: The country code not exist !

### ISSUE THREAD

**Issue by uek06** [SAIC-iSmart-API/saic-home-assistant-addon#57]
Hi,

Since few days add-on is not starting in home assistant.
Version used : 0.5.2.
SAIR_REST_URI : https://gateway-mg-eu.soimt.com/api.app/v1/

Error :

`2024-01-29 22:45:03,072 [ ERROR  ] API call return code is not acceptable: 1000020: {"code":1000020,"message":"The country code not exist !"}. Headers: Headers({'date': 'Mon, 29 Jan 2024 21:45:03 GMT', 'content-type': 'application/x-www-form-urlencoded', 'content-length': '57', 'connection': 'keep-alive', 'x-content-type-options': 'nosniff', 'x-xss-protection': '1; mode=block', 'cache-control': 'no-cache, no-store, max-age=0, must-revalidate', 'pragma': 'no-cache', 'expires': '0', 'x-frame-options': 'DENY', 'app-content-encrypted': '1', 'original-content-type': 'application/x-www-form-urlencoded', 'app-send-date': '1706564703059', 'app-verification-string': 'fadd4f5aa7075074ece924b3343dd7c8a12e9d36ad5d0cedcf444536015ac1bf'}) - saic_ismart_client_ng.api.base
2024-01-29 22:45:03,072 [ ERROR  ] MqttGateway crashed due to SaicApiException - __main__
Traceback (most recent call last):
  File "/usr/src/app/./mqtt_gateway.py", line 322, in run
    login_response_message = await self.saic_api.login()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/base.py", line 71, in login
    result = await self.deserialize(req, response, LoginResp)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/base.py", line 176, in deserialize
    raise se
  File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/base.py", line 166, in deserialize
    raise SaicApiException(error_message, return_code=return_code)
saic_ismart_client_ng.exceptions.SaicApiException: return code: 1000020, message: The country code not exist !
return code: 1000020, message: The country code not exist !
2024-01-29 22:45:03,114 [ ERROR  ] Task was destroyed but it is pending!
task: <Task pending name='Task-1' coro=<Client._resend_qos_messages() running at /usr/local/lib/python3.12/site-packages/gmqtt/client.py:176>> - asyncio
sys:1: RuntimeWarning: coroutine 'Client._resend_qos_messages' was never awaited`

Could you please help ?

Thanks

**Comment by Tonno87** [comment]
From which country do you try to connect to the gateway?

**Comment by uek06** [comment]
France

**Comment by Tonno87** [comment]
Please set the log to debug and post it here without your vin or email.

**Comment by Tonno87** [comment]
Your problem is that you try to login with your phone number. It seems to work only with email as username (at the moment).

@nanomad: Do you know the right syntax to login with the phone number?

**Comment by nanomad** [comment]
@Tonno87 I'll have to address that in the gateway config, the API already supports it

**Comment by nanomad** [comment]
@Tonno87 I've pre-released 0.5.5 which should include the fix for this issue, is it possible to release a "beta" addon version?

The new env variable is called SAIC_PHONE_COUNTRY_CODE, this is what the setup should look like (I'm guessing as I don't have a phone number bound)

Given the following mobile phone number: (+39) 333 12332123

```
SAIC_PHONE_COUNTRY_CODE=39
SAIC_USER=33312332123
SAIC_PASSWORD=Whatever1234
```

**Comment by Tonno87** [comment]
No problem, i will create an addon and test it with my phone number.

**Comment by Tonno87** [comment]
Done:
```
Traceback (most recent call last):
  File "/usr/src/app/./mqtt_gateway.py", line 778, in <module>
    mqtt_gateway = MqttGateway(configuration)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/./mqtt_gateway.py", line 307, in __init__
    phone_country_code=None if username_is_email else self.configuration.phone_country_code,
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Configuration' object has no attribute 'phone_country_code'. Did you mean: 'saic_phone_country_code'?
```

**Comment by nanomad** [comment]
@Tonno87 should be fixed in 0.5.7

**Comment by Tonno87** [comment]
@nanomad  Yes, it's fixed and works now. 

@uek06: You can try it out by installing the new addon with the PreRelease Tag. Search for updates in the addon store and reload the page:
![image](https://github.com/SAIC-iSmart-API/saic-home-assistant-addon/assets/59800400/18c15a84-d381-4a0d-96a4-18413e9d0581)

**Comment by nanomad** [comment]
Cool, I'll remove the pre-release tag as it fixes the door locking as well

**Comment by uek06** [comment]
Thanks guys it works well with the prerelase tag addon !
