### ISSUE TITLE
MG ismart India

### ISSUE THREAD

**Issue by sheminasalam** [SAIC-iSmart-API/saic-home-assistant-addon#6]
Bro appreciate the good work. I have a MG Hector in India which uses [MG ismart app](https://play.google.com/store/apps/details?id=com.saicmotor.iov.india&hl=en_IN&gl=US) for connected features and tracking. The username and login is mobile number and password. Does this addon work for this system?

**Comment by tisoft** [comment]
You would also need to change the api endpoint, since we currently only connect to the European endpoint.

**Comment by Tonno87** [comment]
I will add the "SAIC_URI" env to the addon and update the documentation.

**Comment by Tonno87** [comment]
@sheminasalam: Do you want to find out your Saic URI? Here is how: [Link](https://github.com/SAIC-iSmart-API/reverse-engineering#getting-started)

**Comment by sheminasalam** [comment]
Since I only have phone number and not email address, even if i find the api, would it be of any use?

**Comment by ceaswaran** [comment]
@sheminasalam Did You find it working for MG India app.
My login is mobile number & also SAIC_URI not Known
Please help

**Comment by sheminasalam** [comment]
No, I found the process little cumbersome.

**Comment by ceaswaran** [comment]
Looking forward for a solution
I ideally want an automation in My MG ZS Astor which will disconnect Cars bluetooth from my Phone.
I want to detect Car's Engine status On or OFF which can then disconnect bluetooth immediately.

Currently When am on calls while driving & I park it after my drive My phone BT is connected to car for sometime, during this time infotainment is off & i dont hear any speech. Hence I want Bluetooth to be disconnected a soon as Engine status is OFF

**Comment by Tonno87** [comment]
Look at [issue 10](https://github.com/SAIC-iSmart-API/saic-home-assistant-addon/issues/10#issuecomment-1581164542)
