### ISSUE TITLE
SAIC_PHONE_COUNTRY_CODE not present in 0.5.10

### ISSUE THREAD

**Issue by uek06** [SAIC-iSmart-API/saic-home-assistant-addon#63]
Hi,

Version addon used : 0.5.10 stable (not pre-release)
SAIC_PHONE_COUNTRY_CODE is not present in the configuration tab in home assistant, but in the documentation we can read that this parameter shoud be here.

Can you please help ?

Thanks

**Comment by Tonno87** [comment]
Sry... My fault. Please reinstall the Addon.

**Comment by Tonno87** [comment]
uninstall it, search for updates in the ha addon store, press F5 to refresh the store and reinstall it
