### ISSUE TITLE
[QUESTION] How to set temperature remotely

### ISSUE THREAD

**Issue by fgsch** [SAIC-iSmart-API/saic-home-assistant-addon#66]
👋 First of all, thanks for this awesome addon for HA. I've set it up last night and it's working 👌 .

Now the question, how can I set the remote temperature when enabling remote heating? I have a MG4 and the `climate.XXX_vehicle_climate` only allows me to turn it off or auto. 

I'm using the python gateway v0.5.15 with HA 2024.2.5.

Thank you.

**Comment by Tonno87** [comment]
Hi, same problem? [Issue 48](https://github.com/SAIC-iSmart-API/saic-home-assistant-addon/issues/48)

**Comment by fgsch** [comment]
Yeah, it looks like it. 

So IIUC, the fix is to set the temperature separately, then restart the gateway and turn the climate to auto?

**Comment by Tonno87** [comment]
Publish a Temperature to: saic/<EMAIL>/vehicles/<VIN>/climate/remoteTemperature with Mqtt and it should work after a restart.

![Screenshot_20240301-055345.png](https://github.com/SAIC-iSmart-API/saic-home-assistant-addon/assets/59800400/90028485-a1af-4da6-bad1-ba0fca3e9b30)

**Comment by fgsch** [comment]
Ok, I will give it a go. I was under the impression that this should work automatically in 0.5.15 but something is missing probably.

**Comment by nanomad** [comment]
Yeah sorry, it had been fixed in the 0.6.x version which is in pre-release.

Feel free to try that version, but be aware that there may be regressions

**Comment by fgsch** [comment]
@nanomad Thanks and no worries! I'm going to give the prerelease a try during the weekend.
I will close this ticket for now.
