### ISSUE TITLE
Question: Are multiple cars supported?

### ISSUE THREAD

**Issue by DCSBL** [SAIC-iSmart-API/saic-home-assistant-addon#75]
My partner is getting a new car, we would have 2 MGs then, does this integration allows that somehow?

I couldn’t find this information so please if this is documented you can refer to this.

**Comment by nanomad** [comment]
They are :)

No need to do anything specific beside supplying a different ABRP token for the other VIN

**Comment by DCSBL** [comment]
That is awesome! I will reflect on this when we got the car 👍

**Comment by DCSBL** [comment]
This worked flawlessly! Thanks ✌️
