### ISSUE TITLE
Imperial Measurement

### ISSUE THREAD

**Issue by a-d-r-i-a-n-d** [SAIC-iSmart-API/saic-home-assistant-addon#76]
Hi,

Could we please add an environment variable to set the measurement to imperial instead of metric? The current values are in km so you'd have to convert miles using math. I live in UK and the python MQTT gateway works great with my MG4 Xpower. Many thanks to all contributors, very much appreciated!

**Comment by nanomad** [comment]
Contributions are welcome.

If you use home assistant you can change the unit of measure of the sensor and it will do the conversion for you :)

**Comment by a-d-r-i-a-n-d** [comment]
Thanks for the tip @nanomad , works like a charm in HA!
