### ISSUE TITLE
Add to HACS?

### ISSUE THREAD

**Issue by kiss81** [SAIC-iSmart-API/saic-home-assistant-addon#8]
Personally I don't run the Home assistant OS so I can''t add the current version of this addon. But as the new version uses the Python MQTT saic gateway instead of a docker solution it should be possible to add it to HACS?
https://hacs.xyz/

**Comment by Tonno87** [comment]
Hi, both addons are docker based. To connect your car directly we need to create an integration instead of an addon. It's planned for the future.

**Comment by kiss81** [comment]
> Hi, both addons are docker based. To connect your car directly we need to create an integration instead of an addon. It's planned for the future.
Maybe keep it simple for now and make the mqtt (client) part an integration and leave it to the user to install the docker or the python mqtt gateway themselves?

**Comment by DCSBL** [comment]
We also can see if we can use '[MQTT Discovery](https://www.home-assistant.io/integrations/mqtt/#mqtt-discovery)' in Home Assistant. When using some magic topics/values HA can auto-generate a 'device'.

**Comment by kiss81** [comment]
> To clarify: Both addons in this repository are using mqtt, at the moment there is no "client part" in Home Assistant. After starting the addons you need to configure all mqtt sensors yourself. It is only an alternative way to avoid installing an additional docker instance!
> 
> My plan is to create an integration to avoid the manual config. But my time is rare at the moment :)

My bad: I thought this adding was also including the client part.

**Comment by kiss81** [comment]
Thank you: runs so great at the moment!

**Comment by ppnacho** [comment]
hi, what about this? Is there any news about the integration from HACS? Thanks

**Comment by Tonno87** [comment]
You can try out the python gateway with auto discovery. It creates a mqtt device with all sensors and switches. No need for an hacs integration anymore. 
![Screenshot 2024-01-22 20 19 13](https://github.com/SAIC-iSmart-API/saic-home-assistant-addon/assets/59800400/f46507a2-d73c-470b-bc54-1e31b859b619)

**Comment by ppnacho** [comment]
Hi, I've installed this package in a container, but I have some problem
with the SAIC credentials. I don't know if the user is the phone number or
another string. Do you know how is the format of environment variables??

Thanks

**Comment by Tonno87** [comment]
The username is an e-mail or phone number with this format: yyy-xxxxxxxx. yyy is the country code like 049 for germany.

**Comment by ppnacho** [comment]
Thanks, I will check it.
