### ISSUE TITLE
SoC Target

### ISSUE THREAD

**Issue by coolrunning5360** [SAIC-iSmart-API/saic-home-assistant-addon#94]
Is it possible to set the target SoC in 5% increments rather than just 10% increments? Or is this not supported by the API or the MG4? I would like to be able to set the target SoC to 95%.

**Comment by nanomad** [comment]
Unfortunately it's not supported by the car or the api

Il Ven 24 Mag 2024, 21:50 coolrunning5360 ***@***.***> ha
scritto:

**Comment by coolrunning5360** [comment]
Its Working with the Automation.
