### ISSUE TITLE
No windows status or control on MG5

### ISSUE THREAD

**Issue by svenove** [SAIC-iSmart-API/saic-home-assistant-addon#95]
All windows on my MG5 are always “closed” and issuing “open window” doesn’t do anything either. 

When trying to open, this error is thrown:
```
2024-05-25 17:36:10,453 [ ERROR  ] Unsupported topic windows/driver - __main__
Traceback (most recent call last):
  File "/usr/src/app/./mqtt_gateway.py", line 391, in handle_mqtt_command
    await self.vehicle_state.configure_by_message(topic=topic, payload=payload)
  File "/usr/src/app/vehicle.py", line 569, in configure_by_message
    raise MqttGatewayException(f'Unsupported topic {topic}')
exceptions.MqttGatewayException: Unsupported topic windows/driver

**Comment by nanomad** [comment]
Does the MG5 support window control from the MG app? We have yet to find a car that does have it so that command is not implemented yet

**Comment by svenove** [comment]
Ah, good point. I just expected it to be implemented since the windows were there. 

Can I suggest disabling the window-entities as default, to avoid confusion? :)

**Comment by nanomad** [comment]
> Ah, good point. I just expected it to be implemented since the windows were there.
> 
> Can I suggest disabling the window-entities as default, to avoid confusion? :)

I'm logging a feature request to move them to sensor instead of a switch entity, yes
